-- Add version column for optimistic locking (@Version) to all entity tables

ALTER TABLE member ADD COLUMN version SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE member_status_history ADD COLUMN version SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE member_subscription ADD COLUMN version SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE membership_type ADD COLUMN version SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE payment ADD COLUMN version SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE payment_document ADD COLUMN version SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE session ADD COLUMN version SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE session_occurrence ADD COLUMN version SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE trainer ADD COLUMN version SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE trainer_settings ADD COLUMN version SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE trainer_log ADD COLUMN version SMALLINT NOT NULL DEFAULT 0;
